/* tslint:disable */
/* eslint-disable */
export const __wbg_validationresult_free: (a: number, b: number) => void;
export const diff_gtfs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const validate_gtfs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const validate_gtfs_json: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const validationresult_error_count: (a: number) => number;
export const validationresult_html: (a: number, b: number) => void;
export const validationresult_info_count: (a: number) => number;
export const validationresult_is_valid: (a: number) => number;
export const validationresult_json: (a: number, b: number) => void;
export const validationresult_take_html: (a: number, b: number) => void;
export const validationresult_take_json: (a: number, b: number) => void;
export const validationresult_take_timings_json: (a: number, b: number) => void;
export const validationresult_timings_json: (a: number, b: number) => void;
export const validationresult_truncated: (a: number) => number;
export const validationresult_warning_count: (a: number) => number;
export const version: (a: number) => void;
export const init: () => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => number;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_export: (a: number) => void;
export const __wbindgen_export2: (a: number, b: number, c: number) => void;
export const __wbindgen_export3: (a: number, b: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
